version: "3.2"

services:
  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practicals
    volumes:
      - ./sqldump:/docker-entrypoint-initdb.d